services:
  - type: web
    name: defect-system
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: HIVEMQ_USER
        sync: false
      - key: HIVEMQ_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
